n1 = int(input("ingrese un numero: "))
n2 = int(input("ingrese otro numero: "))
n3 = int(input("ingrese otro numero: "))
n4 = int(input("ingrese otro numero: "))
print("la suma es: ", n1 + n2 + n3 + n4)